apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: knative-components
  namespace: flux
spec:
  interval: 60m
  path: ./toolchain/knative/components
  prune: true
  validation: client
  dependsOn:
    - name: knative-eventing
  sourceRef:
    kind: GitRepository
    name: cluster-system