apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: knative-operator
  namespace: flux
spec:
  interval: 60m
  path: ./knative
  prune: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: cluster-system