---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 60m
  ref:
    tag: "1.8.2"
  url: https://github.com/istio/istio

