---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 500m0s
  path: ./manifests/charts/istio-control/istio-discovery
  prune: true
  dependsOn:
    - name: istio-base
  sourceRef:
    kind: GitRepository
    name: istio
  validation: client

