---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 60m
  ref:
    branch: "release-1.7"
  url: https://github.com/istio/istio

