apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: seldon-toolchain
  namespace: flux-system
spec:
  interval: 60m
  path: ./toolchain/seldon
  prune: true
  validation: client
  dependsOn:
    - name: istiod
  sourceRef:
    kind: GitRepository
    name: cluster-system
