---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system  # client folder
  validation: client

