---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux
spec:
  interval: 10m0s
  path: ./secrets
  prune: true
  # healthChecks:
  #   - apiVersion: helm.toolkit.fluxcd.io/v1beta1
  #     kind: HelmRelease
  #     name: sealed-secrets
  #     namespace: flux
  sourceRef:
    kind: GitRepository
    name: cluster-system
  validation: client

