---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nats-streaming
  namespace: flux
spec:
  interval: 10m0s
  path: ./nats-eventing
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-system
  validation: client

